[package]
name = "nes-emulator"
version = "0.1.0"
edition = "2024"

[dependencies]
lazy_static = "1.4.0"
bitflags = "1.2.1"

sdl2 = "0.34.0"
rand = "=0.7.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
derive_more = { version = "2.0.1", features = ["display"] }
